rules:
  # Ignore "whitelist" - this is used in pylint configuration.
  - name: whitelist
  # Ignore "master" - While https://github.com/canonical/redis-k8s-operator/pull/78
  # is not merged
  - name: master
