name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-22.04
    if: ${{ !failure() }}
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: python3 -m pip install tox
      - name: Run integration tests
        env:
          GITHUB_TOKEN: ${{ github.token }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          tox -e test