name: Charm Integration tests

on:
  pull_request:
    branches-ignore:
      - 'test-branch/**'

jobs:
  charm-integration-test:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.1/stable
      channel: 1.28-strict/stable
      # TODO: reenable self-hosted runners before merging
      self-hosted-runner: false
      rockcraft-channel: latest/edge
      charmcraft-channel: latest/edge
      test-tox-env: charm-integration-test
      trivy-image-config: "trivy.yaml"
