name: Charm Integration tests

on:
  pull_request:
    branches-ignore:
      - 'test-branch/**'

jobs:
  # Usage of operator workflows requires INTEGRATION_TEST_ARGS to be set with
  # --github-token PAT, where PAT is a GitHub Personal Access Token with sufficient perms for the
  # charm integration test.
  charm-integration-test:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.5/stable
      channel: 1.28-strict/stable
      self-hosted-runner: false # we need a noble runner for python 3.12 but there is currently no edge runner with noble base available
      self-hosted-runner-label: "edge"
      rockcraft-channel: latest/edge
      charmcraft-channel: latest/edge
      test-tox-env: charm-integration-test
      trivy-image-config: "trivy.yaml"
